// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmiwdthzccbznrxlcbez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtaXdkdGh6Y2Niem5yeGxjYmV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDMzMDYsImV4cCI6MjA2MjM3OTMwNn0.GGaRTkHFbtxHbpnn9_BLzC5oCsxGcncRrd_okKfGrCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);